# Creating Tensors

In [1]:
import torch

In [2]:
tensor = torch.tensor([[3,4],
                      [5,6]])
tensor

tensor([[3, 4],
        [5, 6]])

In [3]:
tensor.shape, tensor.ndim

(torch.Size([2, 2]), 2)

# Information about Tensors



1.   Tensors should be right datatype. (tensor.dtype)
2.   Tensors should be right shape. (tensor.shape)
3.   Tensors should be on the right device. (tensor.device)

# Matrix Multiplication

In [4]:
torch.matmul(tensor,tensor)

tensor([[29, 36],
        [45, 56]])

#Finding min, max, mean, sum etc (tensor aggregation)

In [5]:
x = torch.tensor([[3,4],
                 [5,6]])
x.dtype

torch.int64

In [6]:
torch.max(x)

tensor(6)

In [7]:
torch.min(x)

tensor(3)

In [8]:
torch.mean(x.type(torch.float32))

tensor(4.5000)

# Reshaping, stacking, squeezing



In [9]:
x = torch.arange(1,11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [10]:
# Reshaping
X_reshaped = x.reshape(2,5)
X_reshaped, X_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [11]:
# Viewing
x_view = x.view(5,2)
x_view, x_view.shape

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 torch.Size([5, 2]))

In [12]:
x_view[2,0] = 39
x_view, x

(tensor([[ 1,  2],
         [ 3,  4],
         [39,  6],
         [ 7,  8],
         [ 9, 10]]),
 tensor([ 1,  2,  3,  4, 39,  6,  7,  8,  9, 10]))

In [13]:
# Stacking on TOP

x_stacked = torch.stack([x,x,x])
x_stacked, x_stacked.shape

(tensor([[ 1,  2,  3,  4, 39,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4, 39,  6,  7,  8,  9, 10],
         [ 1,  2,  3,  4, 39,  6,  7,  8,  9, 10]]),
 torch.Size([3, 10]))

In [14]:
# Squeeze and Unsqueeze

y = torch.rand(size=(1,3,3))
y, y.shape

(tensor([[[0.2596, 0.0658, 0.2499],
          [0.9487, 0.0015, 0.7393],
          [0.9382, 0.9265, 0.2896]]]),
 torch.Size([1, 3, 3]))

In [15]:
y_squeezed = y.squeeze()
y_squeezed, y_squeezed.shape

(tensor([[0.2596, 0.0658, 0.2499],
         [0.9487, 0.0015, 0.7393],
         [0.9382, 0.9265, 0.2896]]),
 torch.Size([3, 3]))

In [16]:
y_unsqueezed = y_squeezed.unsqueeze(dim=0)
y_unsqueezed, y_unsqueezed.shape

(tensor([[[0.2596, 0.0658, 0.2499],
          [0.9487, 0.0015, 0.7393],
          [0.9382, 0.9265, 0.2896]]]),
 torch.Size([1, 3, 3]))

In [17]:
# Permute

z = torch.rand(3,4)
z, z.shape

(tensor([[0.0495, 0.9021, 0.2395, 0.6507],
         [0.9569, 0.3341, 0.3897, 0.6137],
         [0.1890, 0.1295, 0.8909, 0.0770]]),
 torch.Size([3, 4]))

In [18]:
z_permuted = z.permute(1,0)
z_permuted, z_permuted.shape

(tensor([[0.0495, 0.9569, 0.1890],
         [0.9021, 0.3341, 0.1295],
         [0.2395, 0.3897, 0.8909],
         [0.6507, 0.6137, 0.0770]]),
 torch.Size([4, 3]))

#Indexing

In [19]:
x = torch.rand(3,3,3)
x, x.shape

(tensor([[[0.3693, 0.4306, 0.7936],
          [0.6949, 0.4072, 0.9746],
          [0.7623, 0.4034, 0.6932]],
 
         [[0.5820, 0.3158, 0.5109],
          [0.2966, 0.4334, 0.3102],
          [0.1228, 0.9688, 0.7846]],
 
         [[0.4119, 0.7867, 0.5859],
          [0.8906, 0.1147, 0.4968],
          [0.9770, 0.5886, 0.9763]]]),
 torch.Size([3, 3, 3]))

In [20]:
x[0], x[0][0], x[0][0][0]

(tensor([[0.3693, 0.4306, 0.7936],
         [0.6949, 0.4072, 0.9746],
         [0.7623, 0.4034, 0.6932]]),
 tensor([0.3693, 0.4306, 0.7936]),
 tensor(0.3693))

In [21]:
x[:,:,0]

tensor([[0.3693, 0.6949, 0.7623],
        [0.5820, 0.2966, 0.1228],
        [0.4119, 0.8906, 0.9770]])

#PyTorch and Numpy



*   torch.from_numpy(ndarray) - NumPy array to Torch tensor
*   torch.Tensor.numpy()



In [22]:
import numpy as np

In [23]:
array = np.arange(1.0, 11)
tensor = torch.from_numpy(array)
array, tensor

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

In [24]:
tensor.dtype, array.dtype

(torch.float64, dtype('float64'))

In [25]:
tensor = torch.rand(1,11)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([[0.6509, 0.8186, 0.2584, 0.4785, 0.3814, 0.1765, 0.8238, 0.0860, 0.2686,
          0.0568, 0.9785]]),
 array([[0.65090513, 0.8185809 , 0.25836504, 0.47845572, 0.3813858 ,
         0.17646283, 0.8238022 , 0.08597517, 0.26857966, 0.05682981,
         0.9784685 ]], dtype=float32))

#Reproducibitly

In [26]:
# Set Random seed to create reproducibility in random tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(3,3)

tensor_A, tensor_B, tensor_A == tensor_B

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009],
         [0.2566, 0.7936, 0.9408]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

#Accessing GPU using PyTorch

In [27]:
torch.cuda.is_available()

True

In [28]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [29]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [30]:
# Tensor back on CPU
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu, tensor_back_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))